thoth/storages/graph/janusgraph.py
Skip errors reported by mercator that are not stored in the graph database
anyway. These entries cause exceptions when accessing entries such as name as
these entries in fact do not represent actual packages.
=> Skip mercator errors that are not stored anyway

thoth/storages/graph/janusgraph.py
If performance index is passed as None, goblin validation fails as it expects
performance_index to be float based on models definition.
=> Performance index cannot be passed as None

thoth/storages/ceph.py, thoth/storages/graph/janusgraph.py, thoth/storages/graph/utils.py
seeAlso: https://github.com/ambv/black/issues/315
Signed-off-by: Christoph Görn <goern@redhat.com>
=> ignoring some coala errors

thoth/storages/graph/janusgraph.py
I found this weird behaviour when running adviser against multiple JanusGraph
instances. The original query relied on particular tuple ordering, which looks
like is not guaranteed.
=> Do not rely in Gremlin queries for order of received items

thoth/storages/graph/dgraph.py
If ```name``` key is not present in ```python_package_info["result"]```, a warning should be printed and then continue with a next item
=> Fix python_sync_analysis

thoth/storages/graph/models_base.py
If the target uid is assigned after the hash being computed, we overwrite
already existing vertexes which have same source.
=> Fix computing edge hashes

thoth/storages/graph/dgraph.py
This fixes issue when serializing really large stacks in transitive query. An
example can be tensorflow==1.3.0rc0 which depends on other tensorflow releases
indirectly via tensoflow-tensorboard.
=> Introduce mechanism to avoid gRPC issues when serializing large stacks

thoth/storages/graph/dgraph.py
There are present three values not just two - justification, stack
(requirements and requirements locked) and overall stack score.
=> Fix number of overall results

thoth/storages/graph/dgraph.py
This causes issues in sync - no locked requirements are synced if there is no
report. Locked requirements should be always synced if they are present in the
final adviser report.
=> Fix wrong indentation in adviser results sync

thoth/storages/graph/dgraph.py
Let's encapsulate properties into strings so that queries do not introduce
syntax erros in case of non-alphabeticall characters.
Fixes: #727
=> Provide OS version and name as a string

thoth/storages/inspection_schema.py, thoth/storages/inspections.py, thoth/storages/sync.py
Using https://github.com/alecthomas/voluptuous as suggested by @fridex, validation tests for the schema result of an inspection have been created. In this way we are able to check that the correct output is produced during an inspection before it can be stored on Ceph.
=> New tests for inspection schema check before sync

thoth/storages/graph/models.py, thoth/storages/graph/schema.rdf
We need to have these values indexed as they are queried when in adviser
pipelines.
=> Use index for int values of performance indicators

thoth/storages/__init__.py, thoth/storages/package_analyses.py
This is the directory where package analyzer results will be stored on ceph.
=> PackageAnalysisResultsStore is added

thoth/storages/graph/dgraph.py
The message "Omitting stack as no output Pipfile.lock was provided" should be a warning
=> Change log error to warning

thoth/storages/graph/dgraph.py
The old implementation resolved in syntax errors as AND clause was not properly
handled.
Related: https://github.com/thoth-station/adviser/issues/317
=> Fix handling of query filter

thoth/storages/graph/dgraph.py
... otherwise the casting will fail due to None value.
=> Fix default value to environment variable

thoth/storages/graph/dgraph.py
This is a function which queries DGraph for packages that are not analyzed by Package-Analyzer and returns a list of dictionaries, for example:
```json
[
{
"package_name": "pip",
"package_version": "19.0",
"index_url": "https://pypi.org/simple"
},
{
"package_name": "pip",
"package_version": "19.0",
"index_url": "https://tensorflow.pypi.thoth-station.ninja/index/centos7/cuda9.2+jemalloc/simple"
}
]
```
=> WIP Retrieve packages that are not analyzed by Package-Analyzer

thoth/storages/graph/models.py
Using this approach it is possible to run `graph.drop_all()` and use cascade delete.
=> Implemented CASCADE on delete for Foreign Keys

thoth/storages/graph/postgres.py
We always returned all solved packages, fix what is returned from SQL query.
=> Fix unsolved Python packages query

thoth/storages/graph/postgres.py
This way, graph refresh cronjob, will randomly pick which packages were not yet
resolved and will not keep scheduling always same packages. This behavior is
handy if some solver errors out (we will keep scheduling same solvers).
=> Randomize retrieval of unsolved Python packages

thoth/storages/graph/models.py, thoth/storages/graph/postgres.py
- Created new query for python package versions
- Modified attributes for `PythonPackageVersion` shall always have os_name, os_version, python_version provided during syncs
=> New query for number of versions per Python package name

thoth/storages/graph/postgres.py
The unsolved edge cases returns integer which is a sum with unsolved packages.
=> Fix query to retrieve number of unsolved packages

.zuul.yaml
Generic webhook updated to trigger the build from zuul
Fixes: **trigger-build https://managesf.thoth-station.ninja/logs/15/1551842b300b63296b48777782a0229da78cdcbb/post/trigger-build/e3f5a55/ : FAILURE in 1m 01s**
=> Generic webhook updated to trigger the build from zuul

pyproject.toml, thoth/storages/sync.py
consistency in using the variable force
`force_sync` was being used in *sync_inspection_document* but was being provided `force`.
all the rest of the function used force variable, hence using force here as well.
=> consistency in using the variable force

thoth/storages/sync.py
Fixing the func argument design
document_ids were getting passed to a different arguments.
=> Fixing the func argument design

thoth/storages/sync.py
Fixing the func argument names
**inspection_only_ceph_sync -> only_ceph_sync**
**inspection_only_graph_sync -> only_graph_sync**
=> Fixing the func argument names

thoth/storages/graph/postgres.py
This fixes error during retrieval of hashes when there is queried
PythonPackageVersion table, but this table has no relation to HasArtifact
table.
=> HasArtifact is linked with PythonPackageVersionEntity table

thoth/storages/graph/postgres.py
Let's relax this error until we get all the relevant entries so that we do not
block our ingestion.
=> Relax fatal error on syncing unmatched metadata

thoth/storages/graph/postgres.py
We might get into an issue when metadata cannot be gathered because of
installation issues into the given software environment. This patch addresses
such issue and always tries to pick metadata of a package that were
successfully gathered.
=> Pick metadata which were computed

thoth/storages/graph/postgres.py
Use pre-ping mechanism directly offered by SQLAlchemy to check connection
health.
=> Use default pooling from sqlalchemy

thoth/storages/graph/postgres.py
Fixes: https://github.com/thoth-station/storages/issues/1324
=> Issue warning instead of error for metadata keys not compliant with version 2.1 of core metadata specification.

thoth/storages/graph/postgres.py
- Added missing metadata to the output of get Python Package metadata query
Fixes: https://github.com/thoth-station/user-api/issues/680
```
Test
FUNCTION: get_python_package_version_metadata
INPUTS: {'index_url': 'https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/AVX2/simple', 'package_version': '2.0.0', 'package_name': 'tensorflow'}
RESULTS: {
'author': 'Red Hat Inc.', 
'author_email': 'smodeel@redhat.com', 
'download_url': 'https://github.com/tensorflow/tensorflow/tags', 
'home_page': 'https://www.tensorflow.org/', 
'keywords': 'tensorflow tensor machine learning', 
'license': 'Apache 2.0', 
'maintainer': None, 
'maintainer_email': None, 
'metadata_version': '2.1', 
'name': 'tensorflow', 
'summary': 'TensorFlow is an open source machine learning framework for everyone.', …
```
=> Adjust Python Package Metadata query

thoth/storages/graph/postgres.py, thoth/storages/graph/sql_base.py
If dispose is called in destructor, it fails as some of the objects are already
freed by Python GC collector. This produced annoying warning in logs.
Fixes: #1374
=> Do not dispose engine in destructor

thoth/storages/data/alembic/versions/1fbd52a03c73_adjust_types_for_conv_pi.py
Correct alembic version change which didn't recognize the change from string to an integer.
=> Alembic didn't create correct change in schema

thoth/storages/graph/postgres.py
Fixes: https://github.com/thoth-station/storages/issues/1521
Set a flag for correct package extract results syncing.
=> Set Packages Extract flag is_external to True always

thoth/storages/graph/models.py, thoth/storages/graph/postgres.py, thoth/storages/sync.py
Added build log analysis result observations to graph database
Depends-On: #1510 
Shouldn't break any other components as it is updated a new table into the SQL database.
This requires a schema update and module release.
The PR changes, sync.py, progress.py and model.py adding build logs analysis result to the database.
The result of the build breaker is stated below, based on that a table to store these results is produced.  table : build_log_analyzer_run
```
{
"result": {
"build_breaker": {
"already_satisfied": null,
"source": null,
"target": "six",
"version_installed": null,
"version_specified": "==1.10.0,>=1.11.0,>=1.5,>=1.9.0"
},
"reason": {
"ln": 31,
"msg": "ERROR: ERROR: Could not find a version that matches …
```
=> Added build log analysis result observations to graph database

thoth/storages/graph/postgres.py
Fixes: #1555 
This a fix to a breaking change.
https://github.com/thoth-station/storages/blob/2854f1b8444b873f7050210bccfa758a2d906d3d/thoth/storages/graph/models.py#L144
As the index value is not required.
only package_name and package_version is provided by the build_analyzers, it could be passed to  PythonPackageVersionEntity without the index.
=> Fixed missing index issue

thoth/storages/graph/postgres.py
=> No need to query for package extract run - software environment can be directly used

thoth/storages/graph/postgres.py
Add check in adviser sync when report is not provided by Adviser document
=> Add check in sync when report is not provided by Adviser

thoth/storages/sync.py
With argo workflows, we don't have this function anymore.
=> Move import to local use

thoth/storages/graph/postgres.py
With the fix in https://github.com/thoth-station/adviser/pull/856 we put more pressure on the database that can be easily freed using this fix.
=> Reduce number of queries for environment markers by caching results

thoth/storages/__init__.py
Fixes: https://github.com/thoth-station/storages/issues/1828
Add imports
=> Add import or classes cannot be accessed

thoth/storages/sync.py
https://github.com/thoth-station/amun-api/pull/403
https://github.com/thoth-station/amun-api/pull/431
As Amun API was redesigned, we will no longer query API endpoints to obtain results. We will rather use data placed on Ceph. This will unify graph-sync handling with other jobs. To support this idea, amun-client will be removed from dependencies. Until that point, let's move amun-client imports to local scope as newly generated amun-client will introduce breaking changes.
=> Move imports of amun to local scope

thoth/storages/graph/postgres.py, thoth/storages/graph/postgres_utils.py
Due to issue in `sqlalchmey_utils` which use default postgres database name: https://github.com/kvesteri/sqlalchemy-utils/pull/372
Fixes: https://github.com/thoth-station/thoth-application/issues/41
Adapt methods that were causing issue when the name of the database is not postgres from sqlalchemy utils.
=> Remove methods causing issues during initialization and creation of schema when database has different name than postgres

thoth/storages/graph/postgres.py
Related to #1871 
We map all new requests to `_get_or_create_python_package_index` to the new domain
=> Map old domain to new

thoth/storages/sync.py
adding /aggregated to the end of the path is unnecessary
=> adding aggregated points to wrong location

thoth/storages/graph/postgres.py
https://github.com/thoth-station/package-releases-job/issues/440
`query.all()` return type is `List[result]` not `List[str]`.  `result` can be treated as a `tuple`. So because `query.all()` returns:
```
[("foo",), ("bar",), ("baz",)]
```
for example. We can use list comprehension to turn this into ["foo", "bar", "baz"] to match the type hint return type.  This function is only used in package-releases-job rn so this change will not cause any breakages.  It will fix the bug stated above.
=> query.all returns type List[result] not List[str]

Pipfile.lock
Related-To: https://github.com/thoth-station/storages/pull/1976#issuecomment-689657110
relocked pipfile.lock as the boto package was falling to build for pytest.
Relock the pipfile.lock
=> Relock the pipfile.lock

thoth/storages/graph/postgres.py
Related-To: https://github.com/thoth-station/metrics-exporter/issues/480
Add query for adviser run per source type.
=> Add query for adviser run per source type

thoth/storages/graph/postgres.py
Fixes: https://github.com/thoth-station/storages/issues/2007
Related-To: https://github.com/thoth-station/adviser/issues/1178
Related-To: https://github.com/thoth-station/thoth-application/issues/423
It affects:
that requires new releases after Thoth storages to have SI feature ready.
- Adjust queries due to change in SI schema.
- Introduce query to retrieve packages that has SI information
```
SI analyzed query count: 2
SI analyzed query all: [('fbprophet', '0.4', 'https://pypi.org/simple'), ('rsa', '4.0', 'https://pypi.org/simple')]
SI unanalyzed query count: 36735
Python packages releases 36737
```
=> Adjust SI queries

thoth/storages/graph/models.py, thoth/storages/graph/postgres.py
Related-To: https://github.com/thoth-station/thoth-application/issues/507
Adjust queries for graph-refresh-job to retrieve packages to analyze for SI
Initially:
```
SI analyzed 525
SI unanalyzed 8231
Python packages releases 8756
```
After setting one package to be not downloadable
```
Modified is_downloadable for one package!
SI analyzed 525
SI unanalyzed 8230
Python packages releases 8756
SI unanalyzed not downloadable 1
```
=> Adjust query for new flag is_downloadable

thoth/storages/graph/postgres.py
... to respect API we have in other methods.
=> Raise an exception when the given record was not found

requirements.txt
Related-To: https://github.com/thoth-station/adviser/pull/1572
#2046 
Install thoth-ssdeep requirement for thoth-storages
=> Install thoth-ssdeep requirement for thoth-storages

thoth/storages/graph/postgres.py
Noticed a bug that I didn't catch when testing because the extension was already added to my local DB
=> result must be cast to list

thoth/storages/graph/postgres.py
```
8296.267032623291, "process": 1, "message": "No s2i flag stated in the adviser result 'adviser-77ba12c8'"}
adviser-77ba12c8-2675617601: 2020-12-04T13:20:21.66895335Z Traceback (most recent call last):
adviser-77ba12c8-2675617601: 2020-12-04T13:20:21.670488294Z   File "app.py", line 237, in <module>
adviser-77ba12c8-2675617601: 2020-12-04T13:20:21.67076467Z     cli()
adviser-77ba12c8-2675617601: 2020-12-04T13:20:21.67076467Z   File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 829, in __call__
adviser-77ba12c8-2675617601: 2020-12-04T13:20:21.670938295Z     return self.main(*args, **kwargs)
adviser-77ba12c8-2675617601: 2020-12-04T13:20:21.670938295Z   File …
```
=> Correct error in sorting, use sort()

thoth/storages/graph/postgres.py
See discussion here https://github.com/thoth-station/storages/pull/2134#discussion_r535906381
All the applications that are using this method should reference it with its new name
Rename `get_kebechet_github_installations_count_per_is_active` to `get_active_kebechet_github_installations_repos_count_all` - the use of proper naming convention
@pacospace wrote
> naming convention for get_kebechet_github_installations_count_per_is_active is not respected actually. Whatever is returning type number should be should have _count at the end => get_active_kebechet_github_installations_repos_count_all (Type six naming)
=> Use proper naming convention of type 6

thoth/storages/graph/postgres.py
Fixes: https://github.com/thoth-station/storages/issues/2143
Correct bug in using sort()
=> Use sort() correctly

thoth/storages/graph/postgres.py
Related to both https://github.com/thoth-station/mi-scheduler/pull/58
and https://github.com/thoth-station/common/pull/1054#discussion_r534069107
New `def get_kebechet_github_installations_active(self) -> List[str]:` method
The method returns the string list of all the repositories that have active kebechet installations
=> Add get active installations method

thoth/storages/graph/postgres.py
Related-To: https://github.com/thoth-station/metrics-exporter/issues/549
```
"""Retrieve number of users of adviser per source type.
Examples:
>>> from thoth.storages import GraphDatabase
>>> graph = GraphDatabase()
>>> graph.get_origin_count_per_source_type()
{'GITHUB_APP': 1570, 'KEBECHET': 48, 'JUPYTER_NOTEBOOK': 18, 'CLI': 513}
>>> graph.get_origin_count_per_source_type(distinct=True)
{'GITHUB_APP': 145, 'KEBECHET': 5, 'JUPYTER_NOTEBOOK': 2, 'CLI': 78}
"""
```
=> Add get_origin_count_per_source_type method

thoth/storages/graph/postgres.py
Related-To: https://github.com/thoth-station/storages/issues/2196
```
solvers:
['solver-fedora-31-py37', 'solver-fedora-31-py38', 'solver-fedora-32-py37', 'solver-fedora-32-py38', 'solver-ubi-8-py36']
number:
5
```
The new queries will be used in metrics-exporter, not to look for solver from CM but from database. In this way we know which solvers are present in the database, because in this moment only two solvers are shown from CM but in reality we have data from more solvers already in the database. 
In this way we can see already if there is an inconsistency in the data stored.
Moreover when we show users the solvers we have we should return the number from database.
See SLI report of today:
Parameter | Current value | Change since …
=> Add queries and fix bug discovered

thoth/storages/graph/postgres.py
fix: the arguments for the normalize_os_version function
Related-to: https://github.com/thoth-station/graph-sync-job/issues/557
Basedon: https://github.com/thoth-station/common/blob/e9b1cf969aacd9b9eab892ba7bcc1624aa2af31e/thoth/common/helpers.py#L190
=> fix: the arguments for the normalize_os_version function

thoth/storages/graph/postgres.py
We implement similar logic present for adviser sync. This is important if for some reason unsolved messages sent by provenance checker might not be consumed or they are lost.
Related-To: https://github.com/thoth-station/thoth-application/issues/818#issuecomment-770759067
Tested using: `provenance-checker-210202075859-fc13440741027d96`
=> Sync unresolved packages from provenance checker report

thoth/storages/graph/postgres.py
Add query to correctly retrieve number of user software stacks. Recently we introduced ExternalPythonSoftwareStack table only for users, therefore the query currently used in metrics-exporter reports always 0.
=> Adjust query for user software stack

thoth/storages/graph/postgres.py
Related-To: https://github.com/thoth-station/metrics-exporter/issues/573
Introduce query for number of rows in alembic version table
=> Add query for number of rows in alembic table

thoth/storages/graph/postgres.py
Related-to: https://github.com/thoth-station/graph-sync-job/issues/562
=> Do not enforce Python version being set for non-external images

thoth/storages/result_base.py
Related: https://github.com/thoth-station/storages/pull/2281
Related: https://github.com/thoth-station/storages/pull/2282
To simplify colling, a user can supply `include_end_date ` which will include the `end_date` in the listing.
=> Provide ability to include end_date in the results listing

thoth/storages/graph/postgres.py
Function wasn't working if the entry didn't exist in the database. Here we create if it doesn't exist yet.
=> get or create github kebechet installation

thoth/storages/graph/postgres.py
Wrong indentation causes wrong handling of `only_if_package_seen` logic. The given package is never created if `only_if_package_seen=False`.
=> Fix only_if_package_seen logic handling

thoth/storages/graph/postgres.py
```NameError: name 'ExternalPythonSoftwareStack' is not defined```
=> missing model import for ExternalPythonSoftwareStack

thoth/storages/graph/postgres.py
Fixes: https://github.com/thoth-station/storages/issues/2196
Check sync logic in tables with `os_name`:
In this way we should always find `rhel` instead of `ubi`. All methods have been adjusted for consistency.
=> Consistency for OS name in tables and methods

thoth/storages/graph/postgres.py
Fixes: https://github.com/thoth-station/storages/issues/2188
Fixes: https://github.com/thoth-station/graph-metrics-exporter/issues/17
Related-To: https://github.com/thoth-station/metrics-exporter/issues/704
Introduce query for Index bloat data
```
[{'database_name': 'postgres', 'schema_name': 'public', 'table_name': 'python_package_version', 'index_name': 'python_package_version_index_idx_00', 'bloat_pct': Decimal('54'), 'bloat_mb': Decimal('29'), 'index_mb': Decimal('54.852'), 'table_mb': Decimal('111.344'), 'index_scans': 0}, {'database_name': 'postgres', 'schema_name': 'public', 'table_name': 'python_package_version_entity', 'index_name': 'python_package_version_entity_idx', 'bloat_pct': Decimal('53'), 'bloat_mb': Decimal('20'), …
```
=> Introduce query for index bloat data

thoth/storages/graph/postgres.py
As observed during ingestion, the performance of unsolved query used in graph-refresh-job significantly dropped with more data ingested. After digging into this, the issue seems to be in the rules association that resulted in a sequential scan across the whole table of rules (that has few thousand entries) for each package we ingested. Naturally, this grows significantly. The optimization uses LEFT OUTER JOIN to speed up the query. I tested this query in the stage environment - currently, the query finishes in ~3 seconds (in opposite to hours).
=> Improve performance of the unsolved Python packages query

thoth/storages/graph/postgres.py
This is required for whatprovides method in thamos:
Currently giving multiple results of same packages because of the runtime environment degree of freedom.
=> Add distinct option to method get_python_package_version_import_packages_all

thoth/storages/graph/postgres.py
Related to [#1516 on thoth-application](https://github.com/thoth-station/thoth-application/issues/1516)
Add methods to purge old adviser, solver and package extract documents and to store them to Ceph for future use, that will match the commands implemented on the purge-job repo.
=> Add methods to purge old documents and store them on Ceph

thoth/storages/graph/postgres.py
software environment table columns (env_image_name and env_image_tag) entries were always empty
Example from a v1.3.0 package extract result:
```
"Env": [
"PATH=/opt/app-root/src/.local/bin/:/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
"container=oci",
"SUMMARY=Thoth's Source-to-Image for Python 3.8 applications",
"DESCRIPTION=Thoth's Source-to-Image for Python 3.8 applications. This toolchain is based on Red Hat UBI8. It includes pipenv.",
"STI_SCRIPTS_URL=image:///usr/libexec/s2i",
"STI_SCRIPTS_PATH=/usr/libexec/s2i",
"APP_ROOT=/opt/app-root",
"HOME=/opt/app-root/src",
"PLATFORM=el8",
"NODEJS_VER=14",
"PYTHON_VERSION=3.8",
"PYTHONUNBUFFERED=1",
"PYTHONIOENCODING=UTF-8", …
```
=> Allow syncing non-Thoth env variables from package-extract resul

thoth/storages/graph/postgres.py
Related-To: https://github.com/thoth-station/user-api/issues/1543
=> Extend get_software_environments_all query to provide also package_extract_run id and datetime.

thoth/storages/graph/postgres.py
Related: https://github.com/thoth-station/user-api/pull/1548/
=> Allow sorting and pagination of get_python_package_version_names_all

README.rst
Related to https://github.com/thoth-station/datasets/issues/32
Instructions in docs to access the public Thoth database that will be published on `opf-datacatalog`.
=> Instructions for accessing Thoth's public database on opf-datacatalog

thoth/storages/graph/postgres.py
Related to https://github.com/thoth-station/metrics-exporter/issues/822
- No
- Yes
Implement a query to retrieve the datetime of the last solver synced in the database (see first acceptance criteria of https://github.com/thoth-station/metrics-exporter/issues/822)
=> Retrieve datetime of last synced solver

thoth/storages/graph/postgres.py
Related to https://github.com/thoth-station/metrics-exporter/issues/822 :
- No
- Yes
Query the datetime of the last container image analysis synced in the database. Options could be added to filter the container images similarly to solver documents with `os_name`, `os_version` and `python_version`.
=> Query datetime of last container image analysis synced in the database

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .pre-commit-config.yaml, .prow.yaml, thoth/storages/graph/postgres.py
Update the GitHub issue templates using the ones from the template project.
The main need here was to switch the default issue label to `needs-triage` instead of `triage/needs-information` (the latter is to be added after a review that detects missing information).
Also taking the opportunity to update pre-commit plugins
=> Update issue templates

thoth/storages/result_base.py
While checking why slo-reporter was not able to provide analysis of adviser results. I dig into advise-reproter logic and verified that it was not able to read adviser files, due to a method in thoth-storages.
Iterating over files in a bucket gives empty lists even if files exist because the prefix used to identify them is using a default value which is not updated. The value RESULT_TYPE is fixed: https://github.com/thoth-station/storages/blob/3a365887b3c32fac910d568d277a7c3b8ddd6048/thoth/storages/result_base.py#L94
for example using adviser results store method iterates over the following prefix
`data/aws-prod/adviser/-220310`
which does not identify any files.
This PR modify the method to use the `self.RESULT_TYPE` instead which is …
=> Fix method to iterate on thoth files

thoth/storages/graph/postgres.py
Depends-On: https://github.com/thoth-station/storages/pull/2568
```
graph = GraphDatabase()
graph.connect()
r = graph.get_python_package_version_metadata(
package_name="flatbuffers", package_version="1.12", index_url="https://pypi.org/simple"
)
print(r)
```
```
{'author': 'FlatBuffers Contributors', 'author_email': 'me@rwinslow.com', 'download_url': None, 'home_page': 'https://google.github.io/flatbuffers/', 'keywords': None, 'license': 'Apache 2.0', 'maintainer': None, 'maintainer_email': None, 'metadata_version': '2.1', 'name': 'flatbuffers', 'summary': 'The FlatBuffers serialization format for Python', 'version': '1.12', 'requires_python': None, 'description': 'Python runtime library for use with the `Flatbuffers …
```
=> Adjust query for metadata due to change in schema

thoth/storages/graph/postgres.py
https://github.com/thoth-station/integration-tests/issues/250
When new solver docs are synced they can update package metadata resulting in a new `metadata` row with a unique id. When this is passed to `_get_or_create` along with the other values an IntegrityError is raised because the other params already define a unique entry. However, no entry with the exact **kwargs is found so an error is raised. In this PR I removed the package_metadata_id from the original `_create...` query and then added it using an update statement below.
=> update metadata.id instead of passing it to 'create_ppv'

thoth/storages/__init__.py, thoth/storages/sync.py
Related to https://github.com/thoth-station/thoth-application/issues/2513
- No
Randomizing the solver documents listing is optional.
- Yes
Introduce an optional argument to the [`sync_solver_documents`](https://github.com/thoth-station/storages/blob/d58f8a72787aebcc20a2ff702dc087d1286384dc/thoth/storages/sync.py#L95) method in storages to randomize solver document listing.
=> Randomize solver document listing

thoth/storages/graph/postgres.py
https://github.com/thoth-station/user-api/issues/1743
Adds an option to query the `get_python_package_version_names_all` function with a new param `starts_with`
starts_with will filter the query to only include packages that have a name that starts with starts_with input value
=> added option for starts_with filter on /python/package

thoth/storages/ceph.py, thoth/storages/ceph_cache.py
Related to https://github.com/thoth-station/storages/issues/2666
- No
- Yes
Implement a method to retrieve the time to live of a cached document, considering S3 bucket timezones for different environments.
This implementation is based on the current documents caching time of 2 hours.
=> Retrieve TTL of cached documents

thoth/storages/ceph_cache.py
Related to https://github.com/thoth-station/user-api/issues/1614
Fix required for https://github.com/thoth-station/user-api/pull/1798
- No
- Yes
Convert `self.ceph.retrieve_document_attr(object_key=document_id, attr="LastModified")` object to an offset-aware datetime object to fix the diff between `datetime.now()` (offset-aware) and `self.ceph.retrieve_document_attr(object_key=document_id, attr="LastModified")` (offset-naive).
=> Convert ceph datetime object to be offset-aware

tests/data/result/adviser/adviser-220131050913-b7c4ef0fc532ac45, tests/test_ceph.py, thoth/storages/ceph_cache.py
Fixes https://github.com/thoth-station/storages/issues/2722
Related to https://github.com/thoth-station/storages/issues/2666
- No
- Yes
=> Unit test Ceph cache and fix timezone awareness

thoth/storages/sync.py
Fix the sync_documents formatting
Fixes: https://github.com/thoth-station/storages/issues/2750
- Change `dict.fromkeys` to dict comprehension as dict.fromkeys behave weirdly when value is list.
More info: https://stackoverflow.com/questions/3000468/unwanted-behaviour-from-dict-fromkeys
- fix the handle assignment by changing the `doc.rfind` to `doc.find` , so it get correct prefix.
```
>>> x = "adviser-efa7213babd12911"
>>> x[x.rfind("/")+1: x.find("-")]
'adviser'
```
- we would only like to run sync handlers if the document is having value or None.
=> :face_in_clouds: Fix the sync_documents formatting
