thoth/storages/result_base.py
=> Provide a way to pass bucket prefix explicitly in constructor

Pipfile, Pipfile.lock
Fixes: https://github.com/thoth-station/package-releases-job/issues/16
=> Fix yarl issues

thoth/storages/__init__.py
Reverts thoth-station/storages#113
=> Revert "Release of version 0.5.6"

thoth/storages/graph/models.py
Depends-On: https://github.com/goern/janusgraph-openshift/pull/25
=> Specify Python index from which the package came from

thoth/storages/graph/janusgraph.py
using envvar that are injected by OpenShift to discover janusgraph servcie host and port, this requires that a service called "janusgraph" is created
=> using envvar injected by OpenShift to discover janusgraph service

thoth/storages/graph/janusgraph.py, thoth/storages/graph/models.py
Depends-On: https://github.com/goern/janusgraph-openshift/pull/28
=> Introduce unsolvable flag

thoth/storages/graph/janusgraph.py
Fixes: https://github.com/thoth-station/solver/issues/129
=> Normalize names of packages that are inserted into graph database

thoth/storages/graph/janusgraph.py
=> Introduce methods for checking unsolvable and unparsed packages

thoth/storages/graph/janusgraph.py, thoth/storages/graph/models.py
Depends-On: https://github.com/goern/janusgraph-openshift/pull/29
Fixes: https://github.com/thoth-station/solver/issues/128
=> Introduce unparsed flag

thoth/storages/graph/janusgraph.py
=> Fix unparseable solver result sync

thoth/storages/graph/janusgraph.py
Depends-On: https://github.com/thoth-station/common/pull/194
=> Use common date utilities for creating datetime from timestamp

tests/test_result_base.py
=> Fix pytest4 warning

.coafile, .zuul.yaml, pyproject.toml, thoth/storages/graph/models_base.py, thoth/storages/result_base.py
Depends-On: https://github.com/thoth-station/zuul-test-jobs/pull/12
=> using thoth-pytest job

Pipfile.lock, README.rst
Closes https://github.com/thoth-station/storages/issues/182
=> Update README to include test suite in setup.py

thoth/storages/graph/janusgraph.py
Also adjust performance query to consider performance index for the given set
of packages.
=> Introduce query for querying software stacks

thoth/storages/graph/janusgraph.py
=> Fix typo in retrieve_dependencies(...) query

thoth/storages/graph/janusgraph.py
This way we will be able to ask for results of platform specific solver
results.
=> Add platform specific features to the transitive query

thoth/storages/graph/janusgraph.py
=> Add CVE name when querying for CVEs

.coafile, .zuul.yaml, thoth/storages/graph/janusgraph.py, thoth/storages/graph/models.py
Signed-off-by: Christoph Görn <goern@redhat.com>
=> adopted zuul's new trigger-build job

thoth/storages/graph/models.py
Also make sure HasArtifact is registered in models used.
=> Remove duplicit definition

thoth/storages/graph/janusgraph.py
Related: https://github.com/thoth-station/janusgraph-thoth-config/issues/34
=> Add missing ecosystem in query

thoth/storages/graph/janusgraph.py, thoth/storages/graph/models.py
Relates: https://github.com/thoth-station/janusgraph-thoth-config/issues/41
=> Turn ram size into float to fix serialization/deserialization issues

thoth/storages/graph/janusgraph.py, thoth/storages/graph/models.py
Related: https://github.com/thoth-station/janusgraph-thoth-config/pull/46
=> Make runtime and buildtime environment names shared

thoth/storages/graph/janusgraph.py
* also adjust syncing mechanism into graph
=> Adjust performance query to respect runtime environment

create_schema.py, thoth/storages/graph/models.py, thoth/storages/graph/schema.rdf
* entries in generated file are always sorted alphabetically
* give edges and vertexes name if autogenerated names are not nice
=> Improve schema handling

thoth/storages/graph/dgraph.py, thoth/storages/graph/models_base.py
* handle exception if thoth-storages package was not installed itself
* do not assign uid to edges
=> Minor code fixes

thoth/storages/graph/janusgraph.py
These functions are used for the metrics
=> New functions in janusgraph for metrics exporter

thoth/storages/graph/dgraph.py, thoth/storages/graph/models.py, thoth/storages/graph/schema.rdf
Relevant JanusGraph query:
https://github.com/thoth-station/storages/blob/96b27cd9d536bac2b236c5aaa2655494e964593f/thoth/storages/graph/janusgraph.py#L680
=> Implement query for retrieving solver error count

thoth/storages/graph/dgraph.py
Also report error on data integrity issues
=> Fix query for checking solver document presence

.coafile, thoth/storages/graph/dgraph.py
* add dgraph.py to ignored files, too many files
* fix mixed tabs vs spaces
=> Fix coala complains

thoth/storages/graph/dgraph.py
This way we minimalize upsert collisions.
=> Reorganize Python package creation

.coafile
Related: https://github.com/thoth-station/storages/pull/712
=> Ignore changelog file in coala, it's getting too large

thoth/storages/graph/dgraph.py
As we want to install more solvers, we need to know which packages were solved by existing solvers in subgraph checks. Let's introduce a query which will check if the given package in specific version was solved by specific solver.
For test environment data:
```python
from thoth.storages import GraphDatabase
graph = GraphDatabase()
graph.connect()
print(graph.python_package_version_exists("tensorflow", "1.9.0", "https://pypi.org/simple"))
print(graph.python_package_version_exists("tornado", "5.0.2", "https://pypi.org/simple", "solver-fedora-28-py36"))
print(graph.python_package_version_exists("tornado", "5.0.2", "https://pypi.org/simple", "solver-fedora-29-py36"))
```
=> Check if the given package in the given version was solved by specific solver

thoth/storages/graph/dgraph.py
- Modified logic of ```retrieve_unsolved_python_packages``` to retrieve unsolved python packages for a given solver.
- Modified name of queries to be index agnostic.
=> Modified logic of the query 

thoth/storages/graph/dgraph.py
Fixes: https://github.com/thoth-station/storages/issues/765 and introduce filter for solver. In this way we could also monitor the packages analyzed per solver and create logic to schedule solvers (maybe with Sesheta using management-api) for a specific solver that has not been used much yet.
=> Introduce pagination and solver_name filter

thoth/storages/__init__.py
alphabetically order the files
No changes in code
=> alphabetically order the files

thoth/storages/__init__.py, thoth/storages/buildlogs_analyses.py, thoth/storages/buildlogs_analyses_cache.py
updated adapters for storing build log analysis results and cache
Depends-On: #777
=> updated adapters for storing buildlog analysis results and cache

thoth/storages/graph/dgraph.py
Related: https://github.com/thoth-station/package-releases-job/pull/189
=> Introduce method for creating Python package version entities

thoth/storages/graph/dgraph.py
Fixes https://github.com/thoth-station/adviser/issues/303
Signed-off-by: Marek Cermak <macermak@redhat.com>
modified:   thoth/storages/graph/dgraph.py
=> Require non-null `index_url` and `package_name`

README.rst
Related: https://github.com/thoth-station/management-api/pull/166
=> Document schema hadnling in a living deployment

thoth/storages/graph/dgraph.py, thoth/storages/graph/models.py, thoth/storages/graph/schema.rdf
Created model for package-analysis documents in dgraph
=> sync_package_analysis_documents

thoth/storages/graph/models_base.py
We never assigned anything to vertex cache
=> Fix vertex cache handling

thoth/storages/graph/dgraph.py
Fixes: https://github.com/thoth-station/storages/issues/821
=> Add checks for inspection document syncing

thoth/storages/inspection_schema.py
Related: https://github.com/thoth-station/graph-sync-job/issues/231
=> Inspection specification is a dictionary

thoth/storages/graph/dgraph.py
=> Queries are concurrent, not parallel

thoth/storages/graph/dgraph.py
=> Decrease transitive query depth to address serialization issues

thoth/storages/inspection_schema.py
Modified Inspection schema to test before storing in Ceph
=> Modified Inspection schema

thoth/storages/inspection_schema.py
Corrected voluptuous requirements for inspection schema.
=> Corrected voluptuous requirements for inspection schema

thoth/storages/__init__.py, thoth/storages/graph/dgraph.py, thoth/storages/graph/models.py, thoth/storages/graph/schema.rdf, thoth/storages/sync.py
This is a draft on how to sync package analyzer results.
Requires schema update
=> sync package analyzer results

Pipfile, docker-compose.yaml, tests/graph/test_dgraph.py, thoth/storages/graph/dgraph.py
This way we reduce querying parts of sub-graphs which have common dependencies.
=> Optimize retrieval of transitive queries

thoth/storages/graph/dgraph.py
=> New Dgraph function for PI

thoth/storages/graph/performance.py, thoth/storages/graph/schema.rdf
=> Corrected datatype-error for syncing

Pipfile, Pipfile.lock
=> Solved conflict pinning to older version

thoth/storages/inspection_schema.py
=> Added missing inspection schema checks for voluptuous

thoth/storages/graph/dgraph.py
Fixes https://github.com/thoth-station/storages/issues/842
=> Fix key error 'python'

thoth/storages/graph/dgraph.py
Fixes https://github.com/thoth-station/storages/issues/868
=> Fixes Syncing of Package Extract results

thoth/storages/graph/dgraph.py
This should make sure results of package analyzer is synced correctly.
=> Fix Package Analyzer results syncing

thoth/storages/graph/dgraph.py
Related: https://github.com/thoth-station/python/pull/110
=> Use Python package name normalization from thoth-python module

thoth/storages/graph/dgraph.py
- Changed the function name
- Added start_offest and count
- Removed aliases as we are not using @normalize
=> WIP Minor changes to the function which returns unanalyzed packages

thoth/storages/graph/dgraph.py, thoth/storages/graph/models.py, thoth/storages/graph/schema.rdf
Depends-On: https://github.com/thoth-station/solver/pull/281
=> Add is_provided flag

thoth/storages/graph/dgraph.py
Depends-On: https://github.com/thoth-station/package-analyzer/pull/33
=> Remove index key in syncing

thoth/storages/graph/dgraph.py
Depends-On: https://github.com/thoth-station/package-analyzer/pull/33
=> Add error flag to package analyzer run

thoth/storages/graph/dgraph.py, thoth/storages/graph/models.py
Create representation for versioned symbols in the dgraph and store versioned symbols with associated edges
=> Store symbols

thoth/storages/graph/models_performance.py, thoth/storages/graph/postgres.py
=> WIP: Logic to sync inspection results

thoth/storages/graph/postgres.py
Let's drop this query and introduce performance-indicator specific queries.
=> Drop performance related query

README.rst
Fix base class, also `attr.s` are not used with models.
=> Fix documentation for performance indicators

thoth/storages/graph/postgres.py
- Corrected syncing of Pipfile and Pipfile.lock.
- Corrected upsert sync and Tested.
=> Update inspection sync

thoth/storages/graph/postgres.py
=> Disable connection pooling

thoth/storages/graph/models.py
Fixes: https://github.com/thoth-station/cve-update-job/issues/193
=> Increase advisory message for CVEs

thoth/storages/graph/postgres.py
Related: https://github.com/thoth-station/graph-refresh-job/pull/269
=> Adjust signature of method for retrieving unsolved python packages

thoth/storages/inspections.py
=> New class methods for InspectionStore

thoth/storages/graph/postgres.py
=> Add missing method used to register new packages in package releases

thoth/storages/graph/postgres.py
Also, normalize Python package name where missing.
Fixes: 1013
=> Normalize Python package versions before each insert or query

thoth/storages/graph/postgres.py
=> Make solver name optional when retrieving unsolved packages

README.rst, docker-compose.yaml
=> WIP: Use podman-compose

thoth/storages/graph/models.py, thoth/storages/graph/postgres.py
- New query to count records of `main` tables
- New query to count records of `relation` tables
- Update query to count records of `performance` tables
=> New and updated queries

thoth/storages/graph/postgres.py
=> New query: count software stacks per type

tests/data/schema/metadata_ok_1.json, tests/data/schema/result_ok_analyzer_1.json, tests/data/schema/result_ok_solver_1.json, thoth/storages/result_schema.py
... so that results pass and are correctly stored on Ceph.
Fixes: #1052
=> Add duration to the result schema

thoth/storages/graph/postgres.py
=> New queries for python packages

thoth/storages/graph/postgres.py
=> get_python_package_version_count() query

thoth/storages/graph/postgres.py
=> New python_package_versions_count functions

thoth/storages/graph/postgres.py
=> Created functions for get_python_packages cases

thoth/storages/graph/postgres.py
=> Generalized module variable for count

thoth/storages/__init__.py, thoth/storages/sync.py
Also, do a check for ininspection specific parameters
=> Expose sync_documents outside of module

thoth/storages/graph/postgres.py
Fixes: https://github.com/thoth-station/storages/issues/847
=> Sync duration

thoth/storages/graph/postgres.py
=> Convert function according to new naming convention

thoth/storages/graph/postgres.py
=> Add examples to docstrings

thoth/storages/graph/postgres.py
=> Update functions for metrics according to naming convention

thoth/storages/graph/postgres.py
.. and rewrite variables initialization
=> Add missing import

thoth/storages/graph/postgres.py
Depends-On: https://github.com/thoth-station/solver/pull/329
=> Consistenly sync index_url and package_version

.coafile
=> Increase length file

thoth/storages/data/alembic/versions/e05d6d95ea95_added_pythonpackagemetadata_table.py
=> Fix multiple heads present

thoth/storages/graph/postgres.py
Related-To: https://github.com/thoth-station/cve-update-job/issues/218
=> Handle issues in a better way

thoth/storages/graph/postgres.py
=> Fix version key dereference

.coafile, thoth/storages/graph/postgres.py
=> Query environment markers stored in the database

thoth/storages/graph/postgres.py
=> Fix model assignment when syncing results of Python interpreters

thoth/storages/graph/postgres.py
Fixes: https://github.com/thoth-station/storages/issues/1176
=> Correct query to get metadata for Python Package

thoth/storages/graph/postgres.py
Please consider changes requested from https://github.com/thoth-station/storages/pull/1139/files. Thanks :)
=> Revert "Symbol-API"

thoth/storages/graph/postgres.py
=> Query to retrieve ML frameworks names

thoth/storages/graph/postgres.py
- Update all query names according to Thoth naming convention
- Standardize function tp get PythonArtifact hashes
- Introduce normalization for `package_name `and `package_version` for all queries
=> Query name convention

thoth/storages/graph/postgres.py
Fixes: https://github.com/thoth-station/management-api/issues/269
=> Issue warning if the database schema is not initialized yet in connect

thoth/storages/graph/postgres.py
* no need to have pagination
* fix relation query
=> Fix retrieval of Python digests query

Pipfile, Pipfile.lock, setup.py, thoth/storages/graph/models_performance.py
=> Start using mypy in strict mode

thoth/storages/graph/postgres.py
=> Randomize retrievals of unanalyzed Python packages

thoth/storages/graph/postgres.py
=> Randomize retrieval of unsolved Python packages

thoth/storages/graph/enums.py, thoth/storages/graph/models.py, thoth/storages/graph/postgres.py
=> Introduce enum classes for safe API

thoth/storages/graph/postgres.py
The provious implementation returned all CVEs available.
=> Fix query to CVE for a given python package version entity

thoth/storages/sync.py
=> Sync documents from a local directory if requested

tests/test_result_base.py, thoth/storages/result_base.py
=> Correct errors for mypy

thoth/storages/graph/postgres.py
=> Minor changes

thoth/storages/graph/postgres.py
Standardized sync logic entries for Adviser, Provenance Checker and Dependency Monkey
=> Standardize sync logic entries

thoth/storages/graph/postgres.py
Depends-On: https://github.com/thoth-station/amun-api/pull/259
Fixes: https://github.com/thoth-station/storages/issues/1089
=> Adjust sync for inspections

thoth/storages/graph/postgres.py
=> Correct attribute for metadata Provides-Extra

thoth/storages/graph/postgres.py
=> Optimized/Improved query to retrieve unsolved Python Packages

thoth/storages/graph/postgres.py
=> Adjust output query for metric

docker-compose.yaml
=> Use same version as in the cluster

thoth/storages/graph/postgres.py
Fixes:https://github.com/thoth-station/storages/issues/1271
=> Fix warning for migration configuration check

thoth/storages/graph/models_base.py
Fixes: https://github.com/thoth-station/user-api/issues/635
=> Correct output of queries

thoth/storages/graph/postgres.py, thoth/storages/graph/sql_base.py
=> Use context manager for handling sessions

thoth/storages/exceptions.py, thoth/storages/graph/enums.py, thoth/storages/graph/postgres.py, thoth/storages/graph/query_result_base.py
=> Introduce sorting type in queries

thoth/storages/graph/postgres.py
=> Make library thread safe

.zuul.yaml
Signed-off-by: Christoph Görn <goern@redhat.com>
=> added more builds that need to be triggered

thoth/storages/graph/postgres.py
=> Fix alembic configuration instantiation issues

thoth/storages/graph/postgres.py
Based on number of calls performed in adviser its worth to cache this method.
=> Cache environment marker evaluation result

thoth/storages/graph/postgres.py
=> Correct staticmethod

thoth/storages/data/alembic/env.py, thoth/storages/graph/postgres.py
=> Make some log info optional

tests/data/schema/metadata_ok_1.json, tests/data/schema/result_ok_analyzer_1.json, tests/data/schema/result_ok_solver_1.json, thoth/storages/result_schema.py
Related: https://github.com/thoth-station/analyzer/pull/220
=> Provide OS release schema

thoth/storages/graph/postgres.py
=> Add missing filter in queries

thoth/storages/exceptions.py, thoth/storages/graph/postgres.py
Fixes: https://github.com/thoth-station/storages/issues/934
=> Sync cuda version

thoth/storages/graph/postgres.py
Related-To: https://github.com/thoth-station/storages/pull/1388
=> Fix Automatic Update Failure

thoth/storages/graph/postgres.py
=> Do not show alembic info on configure_logger

thoth/storages/graph/postgres.py
=> Sync package version requested rather than package version reported

thoth/storages/graph/postgres.py
=> Fix keyword argument passing

thoth/storages/graph/postgres.py
=> Fix wrong argument name propagated

thoth/storages/graph/postgres.py
Add missing part in the query.
=> Missing randomize

.github/PULL_REQUEST_TEMPLATE.md
=> correct typo

thoth/storages/graph/models_performance.py, thoth/storages/graph/postgres.py
Inspection sync adjustment due to key change in Amun-API
=> Correct key from inspection output

thoth/storages/graph/postgres.py
=> Fix syncing external software environments coming from adviser

thoth/storages/graph/models_performance.py, thoth/storages/graph/postgres.py
Adjust key for inspection sync.
=> Correct inspection sync key

thoth/storages/graph/postgres.py
=> Introduce a way to parametrize memory cache size

thoth/storages/graph/models.py, thoth/storages/graph/postgres.py, thoth/storages/sync.py
Auto pip and black formatting
Related To : #1509 
It an auto-formatting with pip and black.
The text-editor auto-formats based upon the pip and black plugins on each saves.
Please let me know if this are not proper, i would update my plugins.
=> Auto pip and black formatting

thoth/storages/graph/postgres.py
As minor releases of RHEL are ABI compatible, we should not treat them as
different releases from Thoth point of view.
Once merged, I'll adjust our knowledge base in deployments accordingly.
=> Normalize OS version by discarding any minor release in RHEL release string

thoth/storages/graph/postgres.py
Adjust name of query to follow query name convention.
=> Missing change in query name to follow query name convention

thoth/storages/inspection_schema.py
Add missing key to sync inspections.
=> Add missing key to sync inspections

thoth/storages/graph/postgres.py
Adjust parameter in a query for PI
=> Adjust parameter in query for PI

thoth/storages/inspection_schema.py
=> Make keys Optional

thoth/storages/inspection_schema.py
Related: https://github.com/thoth-station/amun-client/pull/101
=> Add missing keys to inspection schema validation

thoth/storages/graph/postgres.py
Fixes: https://github.com/thoth-station/storages/issues/1438
Query for bloat data.
=> Created query to monitor bloat data

thoth/storages/graph/postgres.py
Fixes: https://github.com/thoth-station/storages/issues/1571
=> Fix OS name synced in container image analysis

thoth/storages/graph/postgres.py
=> Fix inspection syncing for RHEL

thoth/storages/data/alembic/env.py
=> Set default to False to reduce logging

thoth/storages/cli.py
Signed-off-by: Marek Cermak <macermak@redhat.com>
modified:   thoth/storages/cli.py
…
option to exclude models from the generated schema
=> Added option to exclude models from the generated schema

thoth/storages/graph/postgres.py
#1586 
Allow count to be optional to remove limit.
`.limit(None)` evaluates to no limit and will return all.
=> All counts optional

thoth/storages/graph/postgres.py
fixes #1573
Parse package version from image name when it comes from an internal source
=> Address issue #1573

thoth/storages/graph/postgres.py
see https://github.com/thoth-station/storages/pull/1577#discussion_r380245363
This will match minor and major releases and not strings with errant periods at the end.
=> Parse py version

README.rst, docs/conventions/README.md
…
Introduce docs for query name convention.
=> Naming convention for query in Thoth Knowledge Graph

Pipfile, Pipfile.lock
`typeshed` has disappeared from PyPI
=> Remove typeshed dev dependency

README.rst
Correct typos and command in the README.
=> Correct README for graph-backup-job

thoth/storages/graph/postgres.py
=> Fix return value

thoth/storages/graph/postgres.py, thoth/storages/revsolvers.py, thoth/storages/sync.py
=> Add logic for syncing reverse solver result

thoth/storages/graph/postgres.py
Fixes: https://github.com/thoth-station/storages/issues/1737
Add map from `ubi` to `rhel` `os_name`.
=> Map ubi to rhel

thoth/storages/graph/postgres.py
Add query to count a specific table.
=> Add query to count a table

Pipfile.lock, docs/conventions/README.md, thoth/storages/graph/postgres.py
This checks whether a specific python package version has gone missing from an index.  This is required for implementing a sieve to not include missing packages in adviser
=> function for checking current availability of package

thoth/storages/graph/postgres.py
https://github.com/thoth-station/storages/pull/1765
=> Raise NotFoundError if setting is_missing flag for non-existing package

thoth/storages/graph/postgres.py
https://github.com/thoth-station/adviser/pull/976
=> add is_missing flag to depends on query

thoth/storages/graph/postgres.py
Depended on #1768
Method to return the total count of active repositories.
=> Get active count

thoth/storages/graph/postgres.py
=> Perform schema version check only if the database is available

Pipfile.lock
=> Update lock file to fix issues in CI

thoth/storages/__init__.py
=> Remove duplicate imports

thoth/storages/inspections.py
This will break things on metrics-exporter side.
=> Implement adapters for inspections

thoth/storages/__init__.py
=> Add missing exports of inspection adapters

thoth/storages/inspections.py
=> Introduce a method for checking if the given inspection exists

thoth/storages/inspections.py
=> Fix computing batch size of inspection jobs

thoth/storages/exceptions.py, thoth/storages/graph/postgres.py
Remove parts already in thoth-common.
=> Remove parts moved to thoth-common

thoth/storages/inspections.py
=> No inspection result batch size

thoth/storages/inspections.py
=> Remove plural, only one build is done per inspection

thoth/storages/__init__.py, thoth/storages/security_indicators.py, thoth/storages/sync.py
Modify SI classes to have a hierarchy.
=> Adjust SI classes

thoth/storages/inspections.py
=> Do raise on counting, return zero instead

thoth/storages/graph/postgres.py
=> Default platform if not available in the solver document

thoth/storages/graph/postgres.py
Fixes: https://github.com/thoth-station/storages/issues/1906
Correct method in thoth-storages.
=> Use method from thoth-common

docker-compose.yaml
=> Use postgres:10.12 in podman-compose as in the cluster

thoth/storages/graph/postgres.py
https://github.com/thoth-station/adviser/pull/1108
Add cache to getting SI results as well as returning None if it is not set.
=> add cache and return None if empty

thoth/storages/graph/postgres.py
Fixes: https://github.com/thoth-station/revsolver/issues/21
=> Fix revsolver syncing logic

thoth/storages/data/alembic/versions/83e2900c3721_add_performance_and_security_enums_for_.py, thoth/storages/graph/enums.py
=> Add security and performance database enums

thoth/storages/graph/postgres.py
Improve warning message produced by showing library heads and database heads to
logs.
=> Add information about heads on schema up2date check

thoth/storages/graph/postgres.py
=> Fix logging error when database schema is not up2date

thoth/storages/graph/postgres.py
DependsOn: https://github.com/thoth-station/storages/pull/1954
Fixes: #1951
=> Propagate platform when syncing revsolver results

thoth/storages/graph/postgres.py
Related: https://github.com/thoth-station/storages/issues/1951
=> Propagate platform information in dependents query

README.rst
Fixes: https://github.com/thoth-station/storages/issues/1858
=> State how to install podman and podman-compose

thoth/storages/graph/postgres.py
Introduce query to database for solver document IDs with errors
=> Introduce query for document ids with solver error

thoth/storages/graph/postgres.py
=> Make package version and package index optional in get_depends_on

thoth/storages/graph/postgres.py
Related-To: https://github.com/thoth-station/metrics-exporter/issues/474
Add queries for SI metrics that will be used by metrics-exporter and for SLO-reporter
=> Add queries for SI metrics

thoth/storages/graph/postgres.py
Fixes: https://github.com/thoth-station/thoth-application/issues/442
Fix security sync
=> Fix sync for security

thoth/storages/graph/postgres.py
https://github.com/thoth-station/thoth-application/issues/507
=> add func for updating downloadable function

thoth/storages/graph/postgres.py
=> Correct docstring

thoth/storages/data/alembic/versions/4461784e248a_added_kebechet_manager_and_last_run_.py, thoth/storages/graph/postgres.py
Fix alembic timeline 
And added a method to fetch active managers for a kebechet repo, and also added the timestamp at repo installation method. 
Related #2016
=> Alembic timeline fix

thoth/storages/graph/postgres.py
Related-To: https://github.com/thoth-station/thoth-application/issues/507
See: https://github.com/thoth-station/storages/pull/2033/files
=> Correct queries after changes in schema

thoth/storages/data/alembic/versions/4461784e248a_added_kebechet_manager_and_last_run_.py
=> Adjust docstring revision

thoth/storages/graph/postgres.py
=> Fix cache handling and add ability to drop the cache

thoth/storages/graph/postgres.py
=> Adjust query filters

thoth/storages/provenance.py
Fixes: https://github.com/thoth-station/thamos/issues/489
=> Match location where provenance-checker documents are stored

thoth/storages/result_base.py
... let's provide a mechanism to store documents that correspond to user requests. This will tackle https://github.com/thoth-station/thoth-application/issues/568 where we will be able to trace accepted user requests but queued in Kafka.
Related: https://github.com/thoth-station/thoth-application/issues/568
=> Provide a method for storing user requests

thoth/storages/graph/postgres.py
Fixes: https://github.com/thoth-station/storages/issues/2073
Adjust DM sync
=> Adjust DM sync

thoth/storages/graph/postgres.py
https://github.com/thoth-station/user-api/issues/794
Gets cuda version found in file and from nvcc command and compare both.
=> check for cuda nvcc and found in file version

thoth/storages/graph/postgres.py
https://github.com/thoth-station/storages/issues/1885
Runs amcheck to check for corruption
1. Check if amcheck is installed
1. if amcheck is not installed, install it
1. run amcheck, if there is an error return true otherwise return false
=> add function to run amcheck and check for db corruption

Pipfile.lock
Fixes: https://github.com/thoth-station/storages/issues/2126
Kebechet update didn't solve the problem: https://github.com/thoth-station/storages/commit/c9c1e469cce7378507d5b54321436c9f8451a5d7
, it was necessary to delete Pipfile.lock and recreate
@fridex @saisankargochhayat @goern @harshad16
=> Adjust constraint on py38

README.rst, thoth/storages/__init__.py, thoth/storages/sync.py
=> Make parameter public

thoth/storages/graph/postgres.py
=> Filter active installations in DB and fix method signature

tests/base.py, thoth/storages/result_base.py
=> Filter out stored requests from listing

thoth/storages/graph/postgres.py
Return wrong output
```
[('CartoonFan/in_xsf',), ('CartoonFan/cantata',), ('CartoonFan/geany-astyle',), ('CartoonFan/flac',), ('CartoonFan/Player',), ('CartoonFan/liblcf',), ('CartoonFan/mkxp',), ('CartoonFan/fluidsynth',), ('CartoonFan/wildmidi',), ('CartoonFan/timidity',), ('CartoonFan/libebur128',), ('CartoonFan/openmugen',), ('CartoonFan/loot',), ('CartoonFan/libloot',), ('CartoonFan/rubberband',), ('CartoonFan/OpenRCT2',), ('CartoonFan/tapir',), ('CartoonFan/autoconf',), ('CartoonFan/libtool',), ('CartoonFan/spcpoint',), ('CartoonFan/gbstag',), ('CartoonFan/gbs-lib',), ('CartoonFan/jbstag',), ('CartoonFan/nsfe-editor',), ('CartoonFan/phoronix-test-suite',), ('CartoonFan/xiphos',), ('CartoonFan/homebank',), …
```
=> Correct-output

thoth/storages/graph/postgres.py
Related-To: https://github.com/thoth-station/report-processing/issues/87
Introduce queries to retrieve specifc document ids according to parameters. All document ids are retrieved by default limited to default count.
=> Introduce queries to retrieve specifc document ids according to parameters

tests/test_buildlogs.py, thoth/storages/buildlogs.py
=> Add prefix for buildlog documents

thoth/storages/graph/postgres.py
Related: https://github.com/thoth-station/thamos/issues/652
=> Normalization functions have been moved to common

thoth/storages/graph/postgres.py
=> Add flters for solver query to retrieve document ids by error

thoth/storages/graph/postgres.py
https://github.com/thoth-station/thoth-application/issues/725
=> remove call to install amcheck on postgres

thoth/storages/graph/postgres.py
Fixes: https://github.com/thoth-station/storages/issues/2185
=> Do not sync Dependency Monkey document if any error is reported

thoth/storages/graph/postgres.py
Depends-On: https://github.com/thoth-station/storages/pull/2193
Related: https://github.com/thoth-station/adviser/issues/1631
=> Create query for querying Thoth's s2i container image symbols

thoth/storages/graph/postgres.py
Related: https://github.com/thoth-station/user-api/issues/1223
=> Introduce queries to query Thoth s2i container images

thoth/storages/solvers.py
Related-To: https://github.com/thoth-station/common/pull/1093/files
Fixes: https://github.com/thoth-station/storages/issues/2205
=> Fix sync solver

thoth/storages/graph/postgres.py
Related: https://github.com/thoth-station/management-api/issues/688
=> Create methods for manipulating with hardware environments

thoth/storages/__init__.py, thoth/storages/dependency_monkey_requests.py
Related: https://github.com/thoth-station/adviser/pull/1670
=> Create an adapter for persisting requests to Dependency Monkey

thoth/storages/graph/postgres.py
thoth-station/kebechet#584
Function for updating Kebechet installation.  This will be used to update based on a users files in their repo.
=> update with pip, piplock, and .thoth.config dicts

thoth/storages/graph/postgres.py
=> Introduce a query for obtaining database size

thoth/storages/graph/postgres.py
Related: https://github.com/thoth-station/thoth-application/issues/1037
Depends-On: https://github.com/thoth-station/storages/pull/2238/
Sync information related to container images that are injected by AICoE-CI.
=> Store information about images produced by AICoE CI on sync

thoth/storages/graph/postgres.py
=> Add filters filtering based on image name

tests/base.py, thoth/storages/ceph.py, thoth/storages/result_base.py
=> Query results on Ceph based on date

thoth/storages/result_base.py
Related: https://github.com/thoth-station/storages/pull/2281
=> Add check for same date supplied for date iteration

thoth/storages/graph/models.py
Closes: https://github.com/thoth-station/storages/issues/2094
=> Remove unused comment

thoth/storages/result_base.py
```
period from 2021-04-01
adviser requests
157
adviser reports
151
period from 2021-04-01
package_extract requests
0
package_extract reports
0
```
=> Extend methods to handle requests

thoth/storages/graph/postgres.py
Related: https://github.com/thoth-station/thoth-application/issues/808
=> Provide methods for deleting data from the database

thoth/storages/graph/postgres.py
=> Make at least one filter mandatory when deleting package-extract runs

.prow.yaml
update the prow jobs resource requests
Prow are failing
Related-to: https://github.com/thoth-station/thoth-application/issues/1332
=> update the prow jobs resource requests

thoth/storages/graph/postgres.py, thoth/storages/sync.py
Fixes: https://github.com/thoth-station/storages/issues/2308
=> Provide force_sync option to solver syncing logic

thoth/storages/graph/postgres.py
Related: https://github.com/thoth-station/adviser/pull/1877
=> Create a query for listing rules assigned for a specific package

thoth/storages/graph/postgres.py
Let's cache entries for better performance in adviser.
=> Cache solver rules retrieval

thoth/storages/__init__.py, thoth/storages/exceptions.py, thoth/storages/logs.py
Related: https://github.com/thoth-station/thoth-application/issues/325
Related: https://github.com/thoth-station/thoth-application/pull/1560
=> Implement adapter for accessing Argo Workflow logs

thoth/storages/graph/postgres.py
Fixes: https://github.com/thoth-station/storages/issues/2336
=> Fix unknown index_url in entity when a rule is assigned

thoth/storages/graph/postgres.py
Related-To: https://github.com/thoth-station/metrics-exporter/issues/174
=> Add method for CVE count

thoth/storages/graph/postgres.py
Related: https://github.com/thoth-station/adviser/issues/1922
=> Introduce query for retrieving RPM packages for a container image analysis

thoth/storages/graph/postgres.py
Related: https://github.com/thoth-station/adviser/pull/1928
=> Introduce query for obtaining last container image analysis

thoth/storages/graph/postgres.py
https://github.com/thoth-station/adviser/issues/1926
=> Cache S2I image symbols query

thoth/storages/graph/enums.py, thoth/storages/graph/models.py, thoth/storages/graph/postgres.py
Related-To: https://github.com/thoth-station/user-api/issues/1454
=> Remove qeb-hwt integration

thoth/storages/graph/enums.py, thoth/storages/graph/postgres.py
Related-To: https://github.com/thoth-station/storages/pull/2386#discussion_r667665441
Related-To: https://github.com/thoth-station/metrics-exporter/issues/559
Adjust enums
Add distinct required for metric
=> Adjust query and enums

thoth/storages/graph/postgres.py
Thanks to @harshad16 for spotting the issue.
Fixes: https://github.com/thoth-station/storages/issues/2397
=> Fix index assignment in solver rule creation

thoth/storages/graph/postgres.py
Related: https://github.com/thoth-station/thoth-application/issues/1850
Related: https://github.com/thoth-station/adviser/pull/2011
=> Introduce query for obtaining trove classfiers

thoth/storages/graph/enums.py
=> Remove unused import

thoth/storages/graph/postgres.py
Related: https://github.com/thoth-station/management-api/issues/790
=> Provide a method for deleting index

thoth/storages/graph/postgres.py
Related-To: https://github.com/thoth-station/thoth-application/issues/1918
=> Modify  get_solved_python_package_versions_software_environment_all method

thoth/storages/graph/postgres.py
Related: https://github.com/thoth-station/user-api/pull/1488
=> Raise if no matching package for the given import was found

thoth/storages/graph/postgres.py
=> Unloop join to index in the unsolved query

thoth/storages/graph/postgres.py
Fixes: https://github.com/thoth-station/metrics-exporter/issues/771
=> Revert removing join index table from query

tests/base.py, tests/test_buildlogs.py, tests/test_result_base.py
Related: https://github.com/thoth-station/micropipenv/pull/207
See: https://github.com/flexmock/flexmock/blob/master/CHANGELOG.md#changed
=> Adjust flexmock import to respect new flexmock release notes

thoth/storages/graph/postgres.py, thoth/storages/graph/sql_base.py
=> Add missing types in function signatures

thoth/storages/graph/postgres.py
Related: https://github.com/thoth-station/support/issues/149
=> Obtain environment markers based on evaluation result

thoth/storages/graph/postgres.py
With this change, we will be able to query imports (prefix query). See examples for more info.
=> Allow querying module imports

thoth/storages/graph/postgres.py
Related: https://github.com/thoth-station/user-api/issues/1539
=> Introduce a query for obtaining environments used to solve a package

thoth/storages/graph/postgres.py
=> Fix condition to identify env vars

thoth/storages/graph/postgres.py
=> Fix return type

thoth/storages/graph/postgres.py
Obtain solver documents based on the supplied python package.
=> Introduce query for obtaining solver documents for the given package

thoth/storages/graph/postgres.py
=> Introduce a query for counting software environments

thoth/storages/graph/postgres.py
Implement this method to properly obtain the number of solved package names. The suggested method in https://github.com/thoth-station/storages/pull/2522#discussion_r773454447 does not work here because it takes into account package version and index url as well.
=> Provide a method that counts number of Python package names

.pre-commit-config.yaml, thoth/storages/graph/postgres.py
Related-To: https://github.com/thoth-station/metrics-exporter/issues/791
=> add query for number of software stacks maintained by kebechet

README.rst
=> Specify command to sync local database instance in documentation

thoth/storages/graph/postgres.py
Related to https://github.com/thoth-station/user-api/issues/1625
Query containerized environments according to specific content (presence of python or RPM package, symbols...)
=> Modify query of containerized environments to get specific content

.thoth.yaml
=> Add my username to maintainers

README.rst
=> Fix formatting of README

thoth/storages/graph/postgres.py
Related to https://github.com/thoth-station/user-api/issues/1645
- No
- Yes
=> Fix container image query

README.rst
=> Fix Ceph variable names and add examples

thoth/storages/result_base.py, thoth/storages/solvers.py
Related: https://github.com/thoth-station/document-sync-job/issues/20
=> Provide a way to iterate over solvers of a specific type

thoth/storages/graph/postgres.py
env_name in dictionary results of get_kebechet_github_installations_info_from_ppv
required for acting on internal triggers
=> add environment name to get_keb_gh_installation_info

thoth/storages/graph/postgres.py
=> remove unusued parameter

.pre-commit-config.yaml, README.rst, docker-compose.yaml
Signed-off-by: Christoph Görn <goern@redhat.com>
=> update to latest pgsql container image

thoth/storages/sync.py
- No
- Yes
Fixing recent issues in syncing of documents. Example:
```
Traceback (most recent call last):
File "app.py", line 252, in <module>
cli()
File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1055, in main
{"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "transport", "lineno": 328, "funcname": "_send_event", "created": 1652190897.622011, "asctime": "2022-05-10 13:54:57,622", "msecs": 622.0109462738037, "relative_created": 8291.739463806152, "process": 1, "message": "Sending event, type:null level:error event_id:f7573cc57fcc4437810916e6b0b63a9a project:1298083 host:sentry.io"}
rv = self.invoke(ctx)
File …
```
=> Fix syncing of documents

thoth/storages/graph/postgres.py
https://github.com/thoth-station/user-api/issues/1743
fixes changes ion the last pr related to the new change: https://github.com/thoth-station/storages/pull/2639
=> changed query to use `like`

.pre-commit-config.yaml, docs/source/conf.py, setup.py, tests/base.py, tests/test_analyses.py, tests/test_ceph.py, tests/test_result_base.py, tests/test_solvers.py, thoth/storages/data/alembic/env.py, thoth/storages/graph/models.py, thoth/storages/graph/postgres.py, thoth/storages/inspections.py, thoth/storages/security_indicators.py
=> Enable pydocstyle pre-commit hook

thoth/storages/ceph.py, thoth/storages/result_base.py, thoth/storages/solvers.py
=> Make _iter_dates_prefix_addition a static method

.thoth.yaml, OWNERS
Include myself as the approver for the repo
Related-to: https://github.com/thoth-station/storages/issues/2682
=> :guardsman: Include myself as the approver for the repo

thoth/storages/ceph_cache.py
Needed as a fix for https://github.com/thoth-station/user-api/pull/1798
- No
- Yes
=> Fix timezone import in ceph cache

.pre-commit-config.yaml, Pipfile, Pipfile.lock, pyproject.toml, thoth/storages/base.py, thoth/storages/buildlogs.py, thoth/storages/ceph.py, thoth/storages/ceph_cache.py, thoth/storages/exceptions.py, thoth/storages/graph/postgres.py, thoth/storages/graph/sql_base.py, thoth/storages/inspections.py, thoth/storages/result_base.py, thoth/storages/security_indicators.py, thoth/storages/solvers.py
- Update + fix pre-commit config
- Fix flake8 pre-commit hooks
- Fix mypy configuration
- Apply https://github.com/hauntsaninja/no_implicit_optional
- Fix mypy errors
=> Fixes: Mypy + pre-commit config

OWNERS
This PR is to add myself to OWNERS as approver and reviewer.
Also removing Maya from the reviewers list to reduce her notifications a bit.
=> Add Pep as an approver / reviewer

thoth/storages/graph/postgres.py
Fix new data causing PythonPackageVersion class IntegrityError
Fixes: https://github.com/thoth-station/solver/issues/5251
-  Moved the values in "get_or_create" which causes errors because its not part of a unique entry
All the details are described here: https://github.com/thoth-station/solver/issues/5251#issuecomment-1380834596
=> Fix new data causing PythonPackageVersion class IntegrityError

thoth/storages/sync.py
followup to #2751
it's an ugly hack but it should work'
=> Fix docs sync, take 2
